import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";


import { api } from "~/utils/api";




export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 max-w-3xl"> 
     <div className="flex justify-end">
      <button type="button" className="text-right font-bold mb-10 ml-20 border-b-2 border-blue-500 ">
      {!user.isSignedIn && <SignInButton />}
      {!!user.isSignedIn && <SignOutButton />}
      </button>
     </div>

      <div className="flex justify-between">
      <h2 className="text-3xl font-bold ml-100 border-b-4 border-blue-500">
        My Shopping Items
      </h2>
      <button type="button" className="bg-red-500 text-white text-sm p-2 rounded hover:bg-black">Add Item</button>
      </div>

      </main>
    </>
  );
}
